<a href="https://colab.research.google.com/github/alishadaudi/ddsa-data-science-project-time-series-prophet/blob/main/Time_Series_Prophet_April_2026.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Code snippet 1
# Installing Prophet for Time Series regression
!pip install Prophet

In [ ]:
# Code snippet 2
# Importing Prophet package
from prophet import Prophet

In [ ]:
# Code snippet 3
# Importing the time series data
import pandas as pd
data = pd.read_csv('https://raw.githubusercontent.com/nvamsimohan/DallasDSA/refs/heads/main/Statefarm%20Incidents.csv')

# Display the data
data

        Date  Incidents
0     3/1/23        364
1     3/2/23        309
2     3/3/23        362
3     3/4/23        320
4     3/5/23        405
..       ...        ...
360  2/24/24        359
361  2/25/24        313
362  2/26/24        410
363  2/27/24        393
364  2/28/24        331

[365 rows x 2 columns]

In [ ]:
# Code snippet 4
# Creating 2 additional columns - ds and y (to satisfy the Prophet package rqmt)
data['ds'] = data['Date']
data['y'] = data['Incidents']

data

        Date  Incidents       ds    y
0     3/1/23        364   3/1/23  364
1     3/2/23        309   3/2/23  309
2     3/3/23        362   3/3/23  362
3     3/4/23        320   3/4/23  320
4     3/5/23        405   3/5/23  405
..       ...        ...      ...  ...
360  2/24/24        359  2/24/24  359
361  2/25/24        313  2/25/24  313
362  2/26/24        410  2/26/24  410
363  2/27/24        393  2/27/24  393
364  2/28/24        331  2/28/24  331

[365 rows x 4 columns]

In [ ]:
# Code snippet 5
# Starting the Prophet  instance
model = Prophet()

In [ ]:
# Code snippet 6
# Building time series model using Prophet
model.fit(data[['ds', 'y']])

In [ ]:
# Code snippet 7
# Predicting the number of Incidents for the next 30 days
future = model.make_future_dataframe(periods=30)
forecast = model.predict(future)
forecast[['ds', 'yhat', 'yhat_lower', 'yhat_upper']]

            ds        yhat  yhat_lower  yhat_upper
0   2023-03-01  259.026623  203.631086  316.961090
1   2023-03-02  237.643865  178.966333  294.771819
2   2023-03-03  290.881506  228.780910  350.668309
3   2023-03-04  280.482373  218.748720  338.703329
4   2023-03-05  283.085281  224.872018  342.096295
..         ...         ...         ...         ...
390 2024-03-25  317.440549  258.918730  377.736647
391 2024-03-26  320.489593  264.112737  381.799337
392 2024-03-27  313.872027  257.651012  370.601653
393 2024-03-28  291.292596  235.025050  347.033416
394 2024-03-29  343.333563  287.567798  401.611121

[395 rows x 4 columns]